config/routes.rb
CSR::Application.routes.draw do
  resources :requests
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  root to: 'requests#index'
  resources :requests

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :title,:image, :budget, :date, :deliverable, :department, :description, :email, :name, :priority, :quantity, :time, :approved, :comments, :status, :jobnumber

  validate :date_is_less_than_one_week_from_today

  #Image Uploader:
  mount_uploader :image, ImageUploader



#Methods:

  def date_is_less_than_one_week_from_today
  	if date<(Date.today+7)
  		errors.add(:date,"-- the Request Date is invalid.")
    end
  end
 

def self.search(search)
  if search
    where('LOWER(name) LIKE ? OR LOWER(title) LIKE ? OR cast(jobnumber as text) LIKE ?', "%#{search.downcase}%", "%#{search.downcase}%","%#{search}%")

  else
    scoped
  end
end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :password, :password_confirmation
  
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.json
  helper_method :sort_column, :sort_direction

before_filter :authorize, only: [:edit, :update, :destroy]


  #GET for search function


  def index

#15/4/13
#Changing the soratable fucntion to a filter this will need to be edited 
    @requests = Request.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @requests }
    # end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        format.html { redirect_to :root, notice: 'Request was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end

 private
  
  def sort_column
    Request.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	
def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class} 
  #Merge Hash params to maintin search sort persistance
end


end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>CSR</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width">

        <%= stylesheet_link_tag "application", :media => "all" %>
                <%= stylesheet_link_tag "main", :media => "all" %>

		
		<%= csrf_meta_tags %>
<!-- Google Analytics Sctipt -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-40701955-2', 'herokuapp.com');
  ga('send', 'pageview');

</script>
<!-- End Google Analytics Script -->

    </head>
    <body>

       
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->


        <div class="logo abs">
           <a href="/"><img src="http://www.lillypulitzer.com/assets/images/text/english/logo.png" height=46 width=169  /> </a> 
        </div>


        <div class="logoBg abs maxW rightalignidth">

        </div>


        <div class="shell abs maxWidth">
  
                <div class="user_header printhide rightalign abs2">
        <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log Out", logout_path %>
        <% else %>
         
          <%= link_to "Log In", login_path %>
        <% end %>
          </div>
          <div class="wrapper">
            
            <!-- Begin page content -->
            <article role="primarycontent">

              <!-- Add your site or application content here -->
              <%= yield %>
            </article>
            <!-- End page content -->

             <footer>
                <div class="copyright">
                  <small>&copy; <script>var dt = new Date(); document.write(dt.getFullYear());</script> Lilly Pulitzer</small>
                </div>
           </footer>
         
          </div><!-- /wrapper-->
          
        </div> <!-- /shell -->
       
        <%= javascript_include_tag "application" %>
		
    </body>
</html>

app/views/requests/_blog.html.erb
<!-- <hr> -->

<% @requests.each do |request| %>
    
<div class="section group">
    <!-- date -->
    <div class="group entrydate">
        <div class="col due_date"><%= request.date.strftime("%b %d, %Y") %></div>
    </div>
    <div class="group entry">
        <div class="col span_1_of_12 datecorner"></div>
        <div class="col span_11_of_12 entryborder">
            <div class="col span_5_of_12 projectinfo">
                <!-- Title and Job Number -->
                <div class = "title"><%= link_to request.title,edit_request_path(request) %>, <span class = "jobnumber"><%= request.jobnumber%></span> </div><br/>
                <!-- Name and Title -->
                 <div class = "name" ><%= mail_to request.email, request.name %>, <span class = "dept"><%= request.department%></span> </div> 

            </div>
            <div class="col span_6_of_12 statusinfo">
                <!-- Deliverable -->
                <div class="deliverable

            <%= 
             'print_d ' if request.deliverable == 'Print' 
             %>
            
             <%=
             'digital_d ' if request.deliverable == 'Digital'
             %>
            
            <%=
             'presentation_d ' if request.deliverable == 'Presentation'
             %>

                          <%=
             'booklet_d ' if request.deliverable == 'Booklet'
             %>

             <%=
             'other_d ' if request.deliverable == 'Other'
             %>

            <%=
             'multimedia_d ' if request.deliverable == 'Multi-Media( Print, Digital, etc)'
             %>






             "


             >

                <%= request.deliverable%></div>

                <!-- Status and Priority -->
            <div class = "priority">
              <!--       <%= 'urgent' if request.priority == 'Urgent'
                    %>
                    <%= 'high' if request.priority == 'High'
                    %>
                    <%= 'medium' if request.priority == 'Medium'
                    %>
                    <%= 'low' if request.priority == 'Low'
                    %>
                    "> -->
            <%= request.priority %>, 

            
            <span class = "status"> <%= request.status%></span></div>

                
                <!-- Controls -->

                <div class = "actions printhide"> 
    <td><%= link_to 'Show', request %></td> |
    <td><%= link_to 'Edit', edit_request_path(request) %></td> |
    <td><%= link_to 'Delete', request, method: :delete, data: { confirm: 'Are you sure?' } %></td> </div>
            </div>  
            <div class="clearfix"></div>      
        </div>
    </div>    
</div>

<div class = "section group">


    


    <% end %>

app/views/requests/_form.html.erb
  <%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
   <!--    <p><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</p>
 -->
   <p class = "error"><%= pluralize(@request.errors.count, "error:") %> Please allow for a minimum 1 week lead time. For urgent requests please email <a href = "mailto:kcunningham@lillypulitzer.com?Subject=CSR">Kathleen Cunningham</a> directly</p>


      <ul class ="error">
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Your Name"%><br />
    <%= f.text_field :name %>
  </div>
   <div class="field">
    <%= f.label "Request Title" %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "Your Email" %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :department %><br />  
    <%= f.select :department, [['IT'],['Marketing'],['Account Services'],['E-Commerce'],['General'],['Accounting'],['Retail'],['Visual'],['Merchandising'],['Production'],['Fabric and Trim'],['Tech Design'],['Print Design'],['Fashion Design'],['Print Design'],['Signature Stores'],['Specialtiy Stores'],['Major Stores'],['DC'],['Quality Control']] %>
  </div>
  <div class="field">
    <%= f.label "Date due:" %><br />
    <%= f.date_select :date,:default => 14.days.from_now %>
  </div>
 <!--  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div> 
  --> <div class="field">
    <%= f.label :budget %><br />
    <%= f.number_field :budget %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.select :priority, [['Low'],['Medium'],['High'],['Urgent']] %>
  </div>
  <div class="field">
    <%= f.label :deliverable %><br />
    <%= f.select :deliverable, [['Print'],['Digital'],['Presentation'],['Booklet'],['Multi-Media( Print, Digital, etc)'],['Other']] %>
  </div>
  <div class="textarea_box">
    <%= f.label :description %>
    <p class = "helper_text">Copy/Imagery/Print Suggestions and/or any other important informations<p> 
    <%= f.text_area :description %>
  </div>

  <div class ="field">
    <p>
    <%= f.label "Upload High Definition Image"%> 
    <%= f.file_field :image %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/requests/_form2.html.erb
<p>For Admin only </p>
<%= form_for(@request) do |f| %>
  <% if @request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Job Number" %><br />
    <%= f.number_field :jobnumber %>
  </div>

 <div class="field">
    <%= f.label "Request Title" %><br />
    <%= f.text_field :title%>
  </div>


 <div class="field">
    <%= f.label "Accepted" %><br />
    <%= f.check_box :approved %>
  </div> 

   <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>

   <div class="textarea_box">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :department %><br />  
    <%= f.select :department, [['IT'],['Marketing'],['Account Services'],['E-Commerce'],['General'],['Accounting'],['Retail'],['Visual'],['Merchandising'],['Production'],['Fabric and Trim'],['Tech Design'],['Print Design'],['Fashion Design'],['Print Design'],['Signature Stores'],['Specialtiy Stores'],['Major Stores'],['DC'],['Quality Control']] %>
  </div>

  <p>
  <b> Date Submitted:</b>
  <%= @request.created_at.strftime("%B %d, %Y") %>
</p>


  <div class="field">
    <%= f.label "Requested Date" %><br />
    <%= f.date_select :date %>
  </div>
 <!--  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div> 
  --> <div class="field">
    <%= f.label :budget %><br />
    <%= f.number_field :budget %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.select :priority, [['Low'],['Medium'],['High'],['Urgent']] %>
  </div>
  <div class="field">
    <%= f.label :deliverable %><br />
    <%= f.select :deliverable, [['Print'],['Digital'],['Presentation'],['Booklet'],['Multi-Media( Print, Digital, etc)'],['Other']] %>
  </div>
  <div class="textarea_box">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <p>
  <b>Attached Image:</b> <br>
  <%= image_tag @request.image_url.to_s %>
</p>


  <div class="actions">
    <%= f.submit %>             
  </div>
<% end %>

app/views/requests/_requests.html.erb
<table class = "pretty">
  <tr class = >
    <th><%= sortable "id", "Job Id" %>     </th>
    <th><%= sortable "approved","Accepted"%></th>
    <th><%= sortable "status","Status"%></th>
    <th><%= sortable "name", "Name" %>       </th>
    <th><%= sortable "email", "Email" %>      </th>
    <th><%= sortable "department", "Department" %> </th>
    <th><%= sortable "date", "Date"%>       </th>
 <!-- 
 <th>Time       </th>
 <th>Budget     </th>
<th>Quantity   </th> -->
    <th><%= sortable "priority", "Priority" %>  </th>
    <th><%= sortable "deliverable", "Deliverable" %> </th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @requests.each do |request| %>
  <tr>
    <td><%= link_to request.id, request %></td>
    <td><%= request.approved %> </td>
    <td><%= request.status %> </td>
    <td><%= request.name %></td>
    <td><%= request.email %></td>
    <td><%= request.department %></td>
    <td><%= request.date.strftime("%B %d, %Y") %></td>
<!--     <td><%= request.time %></td>
  <td><%= request.budget %></td>
    <td><%= request.quantity %></td> -->
    <td><%= request.priority %></td>
    <td><%= request.deliverable %></td>
    <td><%= request.description %></td>
    <td><%= link_to 'Show', request %></td>
    <td><%= link_to 'Edit', edit_request_path(request) %></td>
    <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/requests/_show.html.erb
<p>
  <b>Status:</b>
  <%= @request.status %>
</p>
<p>
  <b>Title:</b>
  <%= @request.title %>
</p>

<p>
  <b>DB ID:</b>
  <%= @request.id %>
</p>
<p>
  <b>Accepted:</b>
  <%= @request.approved %>
</p>


<p>
  <b>Name:</b>
  <%= @request.name %>
</p>

<p>
  <b>Email:</b>
  <%= @request.email %>
</p>

<p>
  <b>Department:</b>
  <%= @request.department %>
</p>
<p>
  <b> Date Submitted:</b>
  <%= @request.created_at.strftime("%B %d, %Y") %>
</p>

<p>
  <b> Request Date:</b>
  <%= @request.date.strftime("%B %d, %Y") %>
</p>


<p>
  <b>Budget:</b>
  <%= @request.budget %>
</p>

<p>
  <b>Quantity:</b>
  <%= @request.quantity %>
</p>

<p>
  <b>Priority:</b>
  <%= @request.priority %>
</p>

<p>
  <b>Deliverable:</b>
  <%= @request.deliverable %>
</p>

<p>
  <b>Description:</b>
  <%= @request.description %>
</p>

<p>
  <b>Comments:</b>
  <%= @request.comments %>
</p>

<p>
  <b>Attached Image:</b><br>
  <%= image_tag @request.image_url.to_s %>
</p>

app/views/requests/edit.html.erb
<h1>Editing request</h1>
<%= link_to 'Go home', root_url %> 

<div class="formWrapper">
<%= render 'form2' %>
</div>
<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<header>
<div class ="section group printhide">

	<div class = "col span_6_of_12">
		<h1>Listing requests</h1>
		<div class = "newrequest"><%= link_to 'New Request', new_request_path %> </div><br>
			Sort By: <%= sortable "deliverable", "Deliverable" %>
	</div>

	<div class = "col span_6_of_12 rightalign toprightcolumn">
			
		<%= form_tag requests_path, :method => 'get' do %>
  
    		<%= text_field_tag :search, params[:search] %>
    		<%= submit_tag "Search"%>

    <br>		
    Sort By:    
    <%= sortable "date", "Date" %>,
    <%= sortable "status", "Status" %>, 
    <%= sortable "priority", "Priority" %>,
    <%= sortable "jobnumber", "Job" %>
	</div>
</div>
</header>



 
<p id="notice"><%= notice %></p>


<!-- These are the hidden field tags and they are for maintaining persistance accross seraches and sorts-->

<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>


<!-- This is the search box -->
<div class = "group printhide">
    <!-- Gorup is a row -->

            <div class = "col span_7_of_12">
            </div>

        <div class = "col span_5_of_12">
			
		</div>

<% end %>

</div>
 
<!-- Moved the table to a partial to make it easier to manage 
  -->
<div id="requests"><%= render 'blog' %></div>

<%= will_paginate @requests %>
<br />

app/views/requests/index.js.erb
$('#requests').html('<%= escape_javascript(render("requests")) %>');

app/views/requests/new.html.erb
<h1>New request</h1>

<%= render 'form' %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'show' %>

<%= link_to 'Edit', edit_request_path(@request) %> 

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>